apps/djangoDemo/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^newForm$', views.new, name='newForm'),
    url(r'^newItem$', views.addItem, name='addItem'),
    url(r'^show/(?P<id>\d+)$', views.show, name='show'),
    url(r'^add/$', views.add_to_wishlist, name='add_to_wishlist'),
    url(r'^remove/(?P<id>\d+)$', views.remove_from_wishlist, name='remove'),
    url(r'^delete/(?P<id>\d+)$', views.delete, name='delete'),
    url(r'^logOut$', views.logOut, name='logOut'),

]

user_Login/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.new_login.urls', namespace = 'users')),
    url(r'^wishlist/', include('apps.djangoDemo.urls', namespace='wishlist'))
]

apps/djangoDemo/models.py
from __future__ import unicode_literals
from django.db import models
from ..new_login.models import User

from django.db import models

class ItemManager(models.Manager):
    def addItem(self, data, user_id):
        response = {}
        errors = self.validateItem(data)
        if len(errors) > 0:
            response['added'] = False
            response['errors'] = errors
        else:
            user = User.objects.get(id=user_id)
            new_item = Item.objects.create(item_name = data['name'], user_created=user)
            response['added'] = True
            response['new_item'] = new_item
        return response

    def addwishlist(self, data, user_id):
        response = {}
        other_user = User.objects.get(id=user_id)
        new_item = Item.objects.create(item_name=data['item_name'], user_other=other_user)
        response['added'] = True
        response['new_item'] = new_item
        return response


    def validateItem(self, data):
        errors=[]
        #check if wishlist already exists in DB
        existing_item = self.filter(item_name=data['name'])
        if existing_item:
            errors.append('That item is already on the Wishlist')
        if len(data['name']) < 3:
            errors.append('Wishlist item must at least 3 characters')
        return errors


# Create your models here.
class Item(models.Model):
    item_name = models.CharField(max_length=100)
    user_created = models.ForeignKey(User, related_name='user_created', default=False)
    user_other = models.ForeignKey(User, related_name ='user_other', default=False)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = ItemManager()

apps/djangoDemo/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.urlresolvers import reverse
from .models import Item, ItemManager
from ..new_login.models import User

# Create your views here.
def index(request):
    all_items = Item.objects.all()
    this_user_items = Item.objects.filter(user_other=request.session['id'])
    this_user = User.objects.get(id=request.session['id'])
    other_items = Item.objects.exclude(user_created=this_user)

    context = {
        'all_items': all_items,
        'this_user': this_user,
        'other_items':other_items,
        'this_user_items':this_user_items
    }
    return render(request, 'djangoDemo/index.html', context)

def new(request):
    this_user = User.objects.get(id=request.session['id'])
    context = {
        'this_user': this_user
    }
    return render(request, 'djangoDemo/addItem.html', context)

def show(request, id):
    this_item = Item.objects.get(id=id)
    result = Item.objects.filter(item_name=this_item.item_name)
    context = {
        'name':this_item,
        'this_item': result
    }
    return render(request, 'djangoDemo/show.html', context)

def addItem(request):
    if request.method == 'POST':
        user_id = request.session['id']
        item = Item.objects.addItem(request.POST, user_id)
        if item['added']:
            new_item = item['new_item']
            messages.success(request, new_item.item_name + " was Successfully added to Wish List")
        else:
            for error in item['errors']:
                messages.error(request, error)
    return redirect(reverse('wishlist:index'))

def add_to_wishlist(request):
    if request.method =='POST':
        user_id = request.session['id']
        item_add = Item.objects.addwishlist(request.POST, user_id)
        if item_add['added']:
            messages.success(request, "Item Successfully added to Wishlist")
    return redirect(reverse('wishlist:index'))


def remove_from_wishlist(request, id):
    if request.method == 'POST':
        remove_item = Item.objects.get(id=id)
        print remove_item
        remove_item.delete()
        messages.success(request, remove_item.item_name + " was removed from WishList")
    return redirect(reverse('wishlist:index'))


def delete(request, id):
    Item.objects.get(id=id).delete()
    return redirect(reverse('wishlist:index'))

def logOut(request):
    request.session.clear()
    return redirect(reverse('users:index'))

apps/djangoDemo/templates/djangoDemo/addItem.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    {% load staticfiles %}
    <link rel='stylesheet' href="{%static 'djangoDemo/css/bootstrap.min.css' %}" media="screen" title="bootstrap" charset="utf-8">
  </head>
  </head>
  <body>
    <div class="container">
      <h2>Create a New Wish List Item</h2>
      <div id='productBox'>
        <form action="{% url 'wishlist:addItem' %}" method='POST'>
            {% csrf_token %}
            <p>Item/Product: <input type="text" name='name' class='form-control col-md-6'></p>
            <input type='submit' value='Create' class="btn btn-default">
        </form>
        <a href="{% url 'wishlist:index' %}" class="btn btn-default">Home</a>
        <a href="{%url 'wishlist:logOut'%}" class="btn btn-default">Log Out</a>
      </div>
    </div>
  </body>
</html>

apps/djangoDemo/templates/djangoDemo/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    {% load staticfiles %}
    <link rel='stylesheet' href="{%static 'djangoDemo/css/bootstrap.min.css' %}" media="screen" title="bootstrap" charset="utf-8">
  </head>
  <body>
    <h2>Welcome {{ this_user.first_name }}</h2>
    <a href="{% url 'wishlist:newForm' %}" class='btn btn-default'>Add Item</a>
    {% for message in messages %}
      <h4 class='alert alert-{{message.tags}}'>{{message}}</h4>
    {% endfor %}
    <div class='container bg-info'>
      <h3>Your Wish List: </h3>
        <table class='table table-bordered table-hover'>
          <thead>
            <tr>
              <th>Item: </th>
              <th>Added by:</th>
              <th>Date Added:</th>
              <th>Action: </th>
            </tr>
          </thead>
          {% for item in all_items %}
          <tr>
            <td><a href="{% url 'wishlist:show' id=item.id %}">{{ item.item_name }}</a></td>
            <td>{{ item.user_created.first_name }}</td>
            <td>{{ item.created_at.date }}</td>
            <td>
              {% if item.user_created.id == this_user %}
                <form action="{% url 'wishlist:delete' id=item.id %}" method='POST'>
                  {% csrf_token %}
                  <input type='submit' value ='Delete'>
                </form>
              {% else %}
                <form action="{% url 'wishlist:remove' id=item.id%}" method='POST'>
                  {% csrf_token %}
                  <input type='submit' value ='Remove from Wishlist'>
                </form>
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </table>
    </div>
    <div class='container bg-info'>
      <h3>Other Users' Wish List</h3>
      <table class='table table-bordered table-hover'>
        <thead>
          <tr>
            <th>Item: </th>
            <th>Added by:</th>
            <th>Date Added:</th>
            <th>Action: </th>
          </tr>
        </thead>
        {% for item in other_items %}
          <tr>
            <td><a href="{% url 'wishlist:show' id=item.id%}">{{ item.item_name }}</a></td>
            <td> {{ item.user_created.first_name}}</td>
            <td> {{ item.created_at.date }}</td>
            <td>
              <form action="{% url 'wishlist:add_to_wishlist' %}" method='POST'>
                {% csrf_token %}
                <input type='hidden' name='item_name' value="{{item.item_name}}">
                <input type='submit' value='Add to my Wishlist'>
              </form>
            </td>
        {% endfor %}
      </table>
    </div>
    <a href="{%url 'wishlist:logOut'%}" class="btn btn-default">Log Out</a>
  </body>
</html>

apps/djangoDemo/templates/djangoDemo/show.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    {% load staticfiles %}
    <link rel='stylesheet' href="{%static 'djangoDemo/css/bootstrap.min.css' %}" media="screen" title="bootstrap" charset="utf-8">
  </head>
  </head>
  <body>
    <a href="{% url 'wishlist:index' %}" class='btn btn-default'>Home</a>
    <a href="{%url 'wishlist:logOut'%}" class="btn btn-default">Log Out</a>
    <div class='container'>
      <h2>{{ name.item_name }}</h2>
      <p>Users who added this product/item under their wish list: </p>
      {% for users in this_item %}
        <p> {{users.user_created.first_name}}</p>
        <p> {{users.user_other.first_name }}</p>
      {% endfor %}
    </div>
  </body>
</html>